# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flecli < Formula
  desc "Fast Log Entry (FLE) command line interface."
  homepage "https://github.com/on4kjm/FLEcli"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/on4kjm/FLEcli/releases/download/v0.1.7/FLEcli_0.1.7_macOS_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "68a42f8980b6599ba4ac2a20c58ae385a4cb076a67fecc3476b5845585732d9e"

      def install
        bin.install "FLEcli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/on4kjm/FLEcli/releases/download/v0.1.7/FLEcli_0.1.7_macOS_64-bit.tar.gz", using: CurlDownloadStrategy
      sha256 "256094123ddd599942ffbe460264f708041ce8892c1543861411a7950672f374"

      def install
        bin.install "FLEcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/on4kjm/FLEcli/releases/download/v0.1.7/FLEcli_0.1.7_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "aa1569b86fdae5abf52035e4de405c0c251caa867d1921322c869a4637bb8541"

      def install
        bin.install "FLEcli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/on4kjm/FLEcli/releases/download/v0.1.7/FLEcli_0.1.7_linux_64-bit.tar.gz", using: CurlDownloadStrategy
      sha256 "534f4446e4775e29e6ce5b11629ef759e292a7e6d40461b5b1853ce2e8239648"

      def install
        bin.install "FLEcli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/on4kjm/FLEcli/releases/download/v0.1.7/FLEcli_0.1.7_linux_arm.tar.gz", using: CurlDownloadStrategy
      sha256 "711e11facc39e556389628d3e8f3be245dc4d9a2c5c102e9c6460c23fa04a739"

      def install
        bin.install "FLEcli"
      end
    end
  end

  test do
    system "#{bin}/FLEcli version"
  end
end
