# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flecli < Formula
  desc "Fast Log Entry (FLE) command line interface."
  homepage "https://github.com/on4kjm/FLEcli"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/on4kjm/homebrew-tap/releases/download/v0.1.4/FLEcli_0.1.4_macOS_64-bit.tar.gz", :using => CurlDownloadStrategy
      sha256 "9373f0e32aedd705d6d3702ca0570f0ff77ec10c5df0d7fa842d6a572840c157"

      def install
        bin.install "FLEcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/on4kjm/homebrew-tap/releases/download/v0.1.4/FLEcli_0.1.4_macOS_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "8ac9698aa6a23a557f9ab71f0299aa446ab4ca8abd38a643fe4708c74416c7c2"

      def install
        bin.install "FLEcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/on4kjm/homebrew-tap/releases/download/v0.1.4/FLEcli_0.1.4_Linux_arm.tar.gz", :using => CurlDownloadStrategy
      sha256 "98316293b7d6dc758e068018fd8f9fa6a8d85121c550cd0b71acb6f55640d188"

      def install
        bin.install "FLEcli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/on4kjm/homebrew-tap/releases/download/v0.1.4/FLEcli_0.1.4_Linux_64-bit.tar.gz", :using => CurlDownloadStrategy
      sha256 "0383a272268ec7e84664b79f6a864c9d03ebcf82ed8b54072f26e73f25a260f5"

      def install
        bin.install "FLEcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/on4kjm/homebrew-tap/releases/download/v0.1.4/FLEcli_0.1.4_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "b08fa349da98c32e7ee9842e9f00e5c1171548dfae028fda61ec8cd22c3c82b8"

      def install
        bin.install "FLEcli"
      end
    end
  end

  test do
    system "#{bin}/FLEcli version"
  end
end
