# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JenkinsTopSubmitters < Formula
  desc "Jenkins Submitter Pivot Table analyzer."
  homepage "https://github.com/jmMeessen/jenkins-top-submitters"
  version "1.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jmMeessen/jenkins-top-submitters/releases/download/v1.2.2/jenkins-top-submitters_1.2.2_darwin_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "7cb65ac6db59cc08d5872cc5989dd02eb6c1904a5ab7e2fffafc5b41a776986e"

      def install
        bin.install "jenkins-top-submitters"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jmMeessen/jenkins-top-submitters/releases/download/v1.2.2/jenkins-top-submitters_1.2.2_darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "68f9148f6d031e96c548a83ca17bceac94b20eec5805567e6416b698fa514a4d"

      def install
        bin.install "jenkins-top-submitters"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/jmMeessen/jenkins-top-submitters/releases/download/v1.2.2/jenkins-top-submitters_1.2.2_linux_armv6.tar.gz", using: CurlDownloadStrategy
      sha256 "53c1c1364c986ebd99b7dbaa402e35acc1a8876a5376876aad63f274f4276603"

      def install
        bin.install "jenkins-top-submitters"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jmMeessen/jenkins-top-submitters/releases/download/v1.2.2/jenkins-top-submitters_1.2.2_linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "b6cd67210d245593e075e82a3a6d493cb28c9ad76cb2a2e363ec035cebacb3fa"

      def install
        bin.install "jenkins-top-submitters"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jmMeessen/jenkins-top-submitters/releases/download/v1.2.2/jenkins-top-submitters_1.2.2_linux_amd64.tar.gz", using: CurlDownloadStrategy
      sha256 "fe6fb73ce06c955ecf50567bc114db2db4f7884f251e634040cbe7a0a89ebf60"

      def install
        bin.install "jenkins-top-submitters"
      end
    end
  end

  test do
    system "#{bin}/jenkins-top-submitters version -d"
  end
end
